### ISSUE TITLE
Not working with firefox

### ISSUE THREAD

**Issue by Rtransat** [CWSpear/bootstrap-hover-dropdown#103]
Hi,

Thanks for your plugin but with firefox it doesn't work. (Even with your demo page : https://cameronspear.com/demos/bootstrap-hover-dropdown/)

Tested with FF 35.0.1 and 36.0 on Windows.

**Comment by philjones88** [comment]
works fine in FF 36 on Mac.

**Comment by CWSpear** [comment]
Works for me, too on Windows 8.

The issue may be related to touch-enabled Windows. See #68
