### ISSUE TITLE
iOS - broken on demo and hover doesn't work

### ISSUE THREAD

**Issue by wonderment** [CWSpear/bootstrap-hover-dropdown#104]
Hello,

First, thank you for tackling this and making this repo available (along with Bower).

Secondly, the demo is broken (at least on iPhone 6 in iOS Simulator) for the first Dropdown link where it does not collapse after being pressed on: http://prntscr.com/6cdl1y

Our own project does not drop down at all despite trying both the data attributes and:

```
$('.nav__dd').dropdownHover({delay:10});
```

It works fine elsewhere (Chrome, IE, Safari, FF). We haven't checked Android, just yet.

Thank you for any assistance!

**Comment by CWSpear** [comment]
I don't have an iPhone to test with, but I am going to go ahead and close this, as we're working on the cross-browser quirks in other issues, and since you only testing on the simulator, it's hard to say it wasn't due to that.
