### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by djonatanb** [CWSpear/bootstrap-hover-dropdown#107]
I was not able to getting it working, I have even tried with your example navbar from here https://cameronspear.com/demos/bootstrap-hover-dropdown/ and it didnt work

I'm using Bootstrap v3.3.4,  jQuery JavaScript Library v2.1.3 and Bootstrap Hover Dropdown v2.1.3

What happens is that the dropdown appear but only sporadically, once every 20 times I hover the link with the mouse. 
I did a recording of the behavior here http://cl.ly/363u3g2a060W
Any idea ?

**Comment by CWSpear** [comment]
What browser are you using?

**Comment by CWSpear** [comment]
And which OS?

**Comment by djonatanb** [comment]
Chrome on Mavericks

**Comment by CWSpear** [comment]
You said the demo at https://cameronspear.com/demos/bootstrap-hover-dropdown/ didn't work for you? Works fine for me, and I'm also on Chrome on Mavericks.

**Comment by djonatanb** [comment]
Sorry, I meant that not even copying the html code, that you used for the navbar on your example page, in my project haven't worked

**Comment by djonatanb** [comment]
Sorry, I meant that not even copying the html code, that you used for the navbar on your example page, in my project haven't worked.

If I access your page all the dropdowns are in place.

I tried with the jquery 1.11 too and got the same behavior.

**Comment by CWSpear** [comment]
I don't know. I don't have enough information to really help. Make sure all the files are being included in the correct order.

**Comment by CWSpear** [comment]
Closing as inactive. I am pretty sure the issue lies in the original poster's implementation.
