### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by morrow95** [CWSpear/bootstrap-hover-dropdown#113]
I am using this on my navbar navigation menu and wanted to point out that if you have margins in place then this is going to cause problems.

For example : 
```
<div id="navbar" class="navbar-collapse collapse">
	<ul class="nav navbar-nav">
		<li><a href="#">one</a></li>
		<li><a href="#">two</a></li>
		<li><a href="#">three</a></li>
		<li><a href="#">four</a></li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" role="button" aria-expanded="false">five <i class="fa fa-angle-down"></i></a>
			<ul class="dropdown-menu" role="menu">
			    <li><a href="#">sub1</a></li>
			    <li><a href="#">sub2</a></li>
			    <li><a href="#">sub3</a></li>
			    <li><a href="#">sub4</a></li>
			    <li class="divider"></li>
			    <li><a href="#">sub5</a></li>
			</ul>
		</li>
	</ul>
        ...
```

In the above I have margin: 0 10px on the top level li elements.  With the 10px left and right margin this causes the hover to work sporadically when entering from the left/right.  On the contrary since there is 0 top/bottom margin entering from the top/bottom it will work correctly each time.

I wouldn't exactly call this a bug, but it does limit your use of margin which would be fairly common especially in the case of the navbar.

**Comment by CWSpear** [comment]
You should use padding on the `a` if you want it to trigger the dropdown. This is a classic "button is bigger than click zone" issue.

This is working as intended.
