### ISSUE TITLE
bootswatch incompatibility

### ISSUE THREAD

**Issue by SylverRat** [CWSpear/bootstrap-hover-dropdown#114]
This works perfectly for me with the main bootstrap files, but if the css is changed to one of [bootswatch](https://bootswatch.com), the hover effect becomes incidental, i've done some tests, but can't tell, what the trigger is if it works or not.
Any ideas, please?

**Comment by CWSpear** [comment]
No idea what's going on, but it seems to be isolated to you.

I took the demo in this repo and replaced `http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css` with `https://bootswatch.com/lumen/bootstrap.min.css` (my favorite BootSwatch theme) in the `<head>` and it worked beautifully.

Styles shouldn't affect anything; make sure you're including all the correct JavaScript and in the correct order.
