### ISSUE TITLE
LESS parsing error

### ISSUE THREAD

**Issue by mateuszjarzewski** [CWSpear/bootstrap-hover-dropdown#115]
ParseError: Unrecognised input
in mixins.less on line 3, column 15:

2  // dashed: fix caret size for Mozilla Firefox
3  border-@{base}: @caret-width-base dashed;
4

**Comment by CWSpear** [comment]
This project doesn't use LESS and you don't give any other context...

**Comment by mateuszjarzewski** [comment]
Sorry, wrong project :>
