### ISSUE TITLE
Hovering on padding don't activate dropdown

### ISSUE THREAD

**Issue by Tudumanu** [CWSpear/bootstrap-hover-dropdown#120]
I've made a simple plunker to show when you have a padding on the parent element of dropdown-toggle, it doesn't activate the dropdown...

Plunker (try to hover from the left where there is a padding-left): http://plnkr.co/edit/PIRoqwBKnsYvKe5HxPYP?p=preview

I've solved this by removing the padding or using the following code:
```
$( document ).ready(function() {
  $('.page-header .top-menu .dropdown-toggle').mouseenter(function(){
    $(this).parent().addClass('open');
  });
});
```

**Comment by CWSpear** [comment]
The issue appears to be your `padding-left` on the `li`. Try using `margin-left` (and removing any padding).
