### ISSUE TITLE
Submenu doesn't position itself correct when lacking space to right

### ISSUE THREAD

**Issue by Magnusson435** [CWSpear/bootstrap-hover-dropdown#121]
It seems that the hover code removes the ability for submenus to position them correctly if space is lacking to the right. I've attached 2 images:

1st image (no hover code) - Submenu positions itself correctly to the left when lacking space to the right
![no-hover](https://cloud.githubusercontent.com/assets/13256727/8597794/b4bff6ee-2657-11e5-924b-27bf318fd032.png)

2nd image (hover code) - Submenu remains to the right when lacking space to the right
![hover](https://cloud.githubusercontent.com/assets/13256727/8597798/bcd68dfc-2657-11e5-8f1c-194339a6ddc4.png)

You can see it in action here:
http://www.vaccinationsgruppen.se/

Have I done something wrong or is it a bug in the code?

**Comment by CWSpear** [comment]
What version of `bootstrap` are you using? What version of `bootstrap-hover-dropdown` are you using? `bootstrap` `3.0` (and thus the latest version of `bootstrap-hover-dropdown`) don't support sub menus.

**Comment by Magnusson435** [comment]
What version of bootstrap are you using?
I'm using Roots 6.5.0 which uses Bootstrap 3.0.0

What version of bootstrap-hover-dropdown are you using?
Version: v2.1.3

I see! Too bad, maybe implement it for backward compatibility?

**Comment by CWSpear** [comment]
Not at this time, sorry. Especially for "tweaks for the submenus to work." Feel free to tweak this code as well to try and get it working.

Good luck!
