### ISSUE TITLE
Don't do anything when navbar is collapsed

### ISSUE THREAD

**Issue by jfly** [CWSpear/bootstrap-hover-dropdown#136]
I find it very hard to use a collapsed navbar with this plugin. I think it's better to not do anything when the navbar is collapsed. I added a simple test for if the navbar is collapsed in https://github.com/jfly/bootstrap-hover-dropdown/commit/f426275df84c415435f2c22e2af3da0367bb0052. I am happy to submit a PR if interested!

**Comment by CWSpear** [comment]
It's normally a non-issue (since typically, people don't have the screen that small on desktop), but I think that's an alright thing to include.

**Comment by jfly** [comment]
Haha, for sure people don't have screens that small, but it's not unheard of for me to make my windows that small! I've created a PR [here](https://github.com/CWSpear/bootstrap-hover-dropdown/pull/137). Entering the realm of truly crazy arguments: it's also possible to plug a mouse into your phone.

**Comment by CWSpear** [comment]
Our [biggest issue](https://github.com/CWSpear/bootstrap-hover-dropdown/issues/68) right now are those hybrid desktop Windows machines that have touch screens. There is some promise with [PointerEvents](https://github.com/CWSpear/bootstrap-hover-dropdown/commit/6d1638314fd77d3ef08f32a3bb4e7727f70e9c7a), but it has some drawbacks as well [poor browser support](http://caniuse.com/#feat=pointer) (but all the major vendors have said they'd support it eventually).
