### ISSUE TITLE
Versions do not update on CDNJS.com

### ISSUE THREAD

**Issue by holtkamp** [CWSpear/bootstrap-hover-dropdown#140]
It appears that https://cdnjs.com/libraries/bootstrap-hover-dropdown stopped updating at version ```2.0.10```. Is this process not automatically based on the tags in this repository?

**Comment by CWSpear** [comment]
I have no idea. I didn't set that up, and I think it's been mentioned once as an issue before. 

A quick search brought up issues on the `cdnjs` repo such as https://github.com/cdnjs/cdnjs/pull/3417. Looks like you have to open it up on there. It's difficult for me to keep all the different ways people use this plugin up to date, so if it's something you use/is important to you, it'd be awesome if you would create a PR to `cdnjs`'s repo to get that up to date. Thanks!

**Comment by CWSpear** [comment]
If you _are_ wanting to using a CDN, https://github.com/jsdelivr/jsdelivr updates automatically (and apparently emails me--I had forgotten that, but I just got an email about my most recent update). Might be worth giving them a try.

**Comment by CWSpear** [comment]
Direct link: https://cdn.jsdelivr.net/bootstrap.hover-dropdown/2.2.1/bootstrap-hover-dropdown.min.js

**Comment by holtkamp** [comment]
Pardon my ignorance @CWSpear, will try to come up with something that makes CDNJS update automagically.

**Comment by holtkamp** [comment]
FYI, in the meantime CDNJS is been updated to 2.2.1, next time this mechanism should work automatically. 

https://cdnjs.com/libraries/bootstrap-hover-dropdown

**Comment by CWSpear** [comment]
Thanks!
