### ISSUE TITLE
demo site down?

### ISSUE THREAD

**Issue by Kurdym** [CWSpear/bootstrap-hover-dropdown#142]
The link to the demo site shows a 404.

**Comment by holtkamp** [comment]
:+1: http://cameronspear.com/demos/bootstrap-hover-dropdown/ seems down.

Maybe you can consider:

- remove the link from the documentation and encourage users to clone the repo and check the demo.html locally
- host a static site at https://pages.github.com, works quite easy :smiley:

**Comment by CWSpear** [comment]
This is fixed now. Sorry for the inconvenience!
