### ISSUE TITLE
Problem with hover on <a> ?

### ISSUE THREAD

**Issue by Gaetan-dc** [CWSpear/bootstrap-hover-dropdown#145]
Hi,

I have a problem when using the toggle on an `<a>` element : the hover triggers when I come from below the element, but not from above or the sides.
You can see it here, try to hover "Products" in the top : http://wrap.dynamicweb-cms.com/home-2
Here is what the HTML looks like : 
```html
<li class="dropdown dw-navbar-button">
 <a href="/products-1" data-close-others="true" data-hover="dropdown" class="dropdown-toggle">Products<span></span></a>
    <ul class="M1 dropdown-menu">
      <li class="dropdown">
        <a href="/products-1/bikes">Bikes<span></span></a>
      </li>
      <!-- etc. -->
    </ul>
  </li>
```

If I replace `<a>` by `<button>`, I don't have any problem. I have updated to the latest version locally but no luck.

Any idea where this could come from ?

Thanks !

**Comment by rebdev** [comment]
Pssst: the link you give isn't working.

**Comment by Gaetan-dc** [comment]
Hm, weird. I tried it in incognito mode and on my phone, and I don't have any problem accessing it.

**Comment by CWSpear** [comment]
This is related to #8, #16 and #27. In short, this isn't supported, but it's not a bug either. There are some hacky workarounds, and it's on the roadmap for v3, which is indefinitely stalled (see other v3 tickets for more on that).
