### ISSUE TITLE
Hover works only sometimes

### ISSUE THREAD

**Issue by illycz** [CWSpear/bootstrap-hover-dropdown#151]
Thanks for your plugin.

I have problem when hover works works casually:

![hover](https://cloud.githubusercontent.com/assets/2109984/15268919/2a0fd9f6-19ef-11e6-8967-4abed8493b58.gif)

Thanks for any advice

Patrik

**Comment by CWSpear** [comment]
I couldn't possibly say just based on this. Looks like you may have nonstandard markup that is causing things to not behave as you expect, or even interfering JavaScript.

**Comment by aamjsadiq** [comment]
#153 

Could be related to this issue. @illycz

**Comment by holtkamp** [comment]
@illycz can you provide your example, or preferably a stripped down version on https://jsfiddle.net ?

**Comment by illycz** [comment]
@holtkamp I finally used a different solution so I don't have any example. Sorry

**Comment by holtkamp** [comment]
>I finally used a different solution so I don't have any example. Sorry

ok, then I suggest you to close this issue...
