### ISSUE TITLE
Question re: making parent menu links clickable

### ISSUE THREAD

**Issue by jassibacha** [CWSpear/bootstrap-hover-dropdown#16]
I'm trying to make it so that my primary/parent menu links are clickable, I noticed what I believe to be something similar in the closed issues: https://github.com/CWSpear/twitter-bootstrap-hover-dropdown/pull/8

Essentially, I have 2 links on my primary menu that have dropdowns, but I also need the parent link itself to be clickable.. just trying to figure out the easiest way to do this. Thanks.

**Comment by lorenzosinisi** [comment]
https://github.com/lorenzosinisi/bootstrap-hover-dropdown my fork

**Comment by eye-too** [comment]
Why not use the caret / plus icon / arrow icon for toggle and let the link be a link to another URL? Here is my edit of the MetisMenu to prove the concept of what I am looking for. http://codepen.io/eye-wonder/pen/XNxOqw
I rather like your navigation because it uses the standard bootstrap navigation markup, and it is working on both desktop and mobile. I don't really like hover menus. (I also like the idea of collapsing other parts of the menu tree when opening a submenu on mobile.)

**Comment by DavidInfoAndComp** [comment]
I found a solution. Force the action of <a> tag usign the href property with javascript

```
$( document ).ready(function() {
    $(".dropdown-toggle").click(function(){
       var url = $(this).attr("href"); 
       $(location).attr('href', url);
    });
}); 
```

**Comment by sean-mystyle** [comment]
A client of mine in Shopify had the same issue with a menu that had Mega Menu for 2 out of 5 of the links.  I also got it working to make parent menu links working, its commented out within the code below. 
 Ultimately I wanted links with no child menus to click through to the pages, but menus links with child menus to click and open the menu without clicking through.  Thanks to @DavidInfoAndComp for the parent menu option.

This was my final code:

```html
<script>
    // fixing top level link clicking while mega menus are enabled on some but not all nav items:
    $(document).ready(function() {
        $('.nav ul li > a').each(function() {
            var isMegaParent = $(this).hasClass('mega-menu-parent');
            if (!isMegaParent) {
                $(this).attr('data-dropdown-rel', '');
                $(this).off('click'); // remove mega menu/ dropdown handler for links with no mega menu children
            } else {
                // if you want the parent of mega menus to also click through, enable this:
                /*$(this).click(function(){
       			var url = $(this).attr("href"); 
       			$(location).attr('href', url);
    		   });*/
            }
        });
    }); 
</script>
```
