### ISSUE TITLE
Anchor element gets hidden

### ISSUE THREAD

**Issue by akshoysaha** [CWSpear/bootstrap-hover-dropdown#160]
We have integrated this plugin and we are facing a strange problem. Visit http://119.9.24.53/rangehoods - add a product to cart and you can see 'cart' dropdown on top right. When we hover, the dropdown comes perfectly and move the cursor outside and you can see the entire element gets hidden. This issue was not in previous version.

We used below HTML structure
`<div id="" class="dropdown"> <div class="button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false"...><i class="icon-cart"></i>.............. HTML CONTENT..........</div></div>`

**Comment by CWSpear** [comment]
It appears to be working for me. I don't understand the issue.

Also, please read [GitHub's Markdown guide](https://guides.github.com/features/mastering-markdown/) to make your issues more readable.
