### ISSUE TITLE
Doesn't work on Firefox 57.0.2 (64-bit) 

### ISSUE THREAD

**Issue by Njuhobby** [CWSpear/bootstrap-hover-dropdown#162]
The demo on https://cameronspear.com/demos/bootstrap-hover-dropdown/ doesn't work on Firefox 57.0.2 (64-bit) version

**Comment by CWSpear** [comment]
I just tested it (Firefox is my primary browser, and I have that same exact version) and it worked fine for me.

**Comment by Njuhobby** [comment]
I tested this again on my desktop and it works pretty well. My guess is that because my surface book has a touch screen, and somehow Edge doesn't think surface book's screen is a touch screen but Firefox does.
