### ISSUE TITLE
How to keep Dropdown Menus open?

### ISSUE THREAD

**Issue by ghost** [CWSpear/bootstrap-hover-dropdown#23]
Hi,

first of all thank you for this great bootstrap plugin. I was just about to create this functionality on my own when I found yours :) However, I need it to behave in a special way and I'm not sure if your plugin can support this already.

Is it possible to keep a dropdown menu open, e.q. the dropdown menu of the current webpage?

Let's say I have a Navbar with 3 menu items: "Home", "About Us" and "Services". Each one has a dropdown menu. Now I click open the page "About Us". On this page I want to keep the dropdown menu of the "About Us" menu item always open.

When I hover over the menu item "Services", its dropdown menu should open and hide the other dropdown menus. This is no problem. I can set "data-close-others" to "true". But when I move the mouse pointer away from "Services" menu item and the delay time has elapsed, all dropdown menus are deactivated.

How can I reopen (or keep open) the dropdown menu of the current page?

**Comment by belenusvr** [comment]
hi. 
I  have a similar issue with my hamburger . I think is in this lines  . My burger does not open .

  }
}
nav.opened .hamburger span {
  &:nth-child(1) {
    top: 8px;
    width: 0;
    opacity: 0;
    right: 50%;
    transition: all .2s;
  }
  &:nth-child(2) {
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg);
    transition: all .25s;
  }
  &:nth-child(3) {
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg);
    transition: all .25s;
  }
  &:nth-child(4) {
    top: 8px;
    width: 0;
    opacity: 0;
    right: 50%;
    transition: all .2s;
  }
}
.collapsed {
  &.navbar-expand {
    flex-direction: column;
  }
  .btn {
    display: flex;
  }
  .navbar-collapse {
    display: none !important;
    padding-right: 0 !important;
    &.collapsing,&.show {
      display: block !important;
      .navbar-nav {
        display: block;
        text-align: center;
        .nav-item {
          clear: both;
          & when (@showButtons = false
            }
          }
        }
      }
