### ISSUE TITLE
open again and close

### ISSUE THREAD

**Issue by claudchan** [CWSpear/bootstrap-hover-dropdown#55]
Hi,
I notice that when I mouse over a menu, dropdown-menu just open and it is fine. Then, I try to click it, the dropdown-menu will close this is also correct. And then, I mouse out, here I notice the 'bug' the dropdown-menu will open again and close immediately.

Is there any way can prevent that happen?
I also notice that in your 'Plugin Demo' site the top 'navbar', the first-child dropdown does works very well while the rest after has the same bug. I wonder how did you make it the first-child dropdown working perfectly but not the rest after.

Thanks.

**Comment by diasks2** [comment]
I was experiencing an issue where entering the button from the top would not trigger a hover event (while entering from the side or bottom would). The fix suggested by @palamccc above fixes that though. Is there a reason that his fix was not merged to master?

**Comment by ioncube** [comment]
Just found the same issue too. The release implementation is working seemingly without a problem in an Angular application, but with memory leaks. After updating and re-implementing to eliminate the leaks, the issue showed itself. The suggested fix from @palamccc seems correct.
