### ISSUE TITLE
Dropdown content sometimes disappear automatically.

### ISSUE THREAD

**Issue by kntmrkm** [CWSpear/bootstrap-hover-dropdown#96]
- bootstrap 3.3.1
- bootstrap-hover-dropdown 2.0.11

In my environment, when mouse pointer moving fast to dropdown link.

sometimes, dropdown body disappear automatically.

- Show up any dropdown menu.
- Next, focus to any link of dropdown fast.
  ( late link is often happens.)
- Despite of focus on dropdown body, dropdown will disappear sometimes.

also, you can watch vimeo. http://vimeo.com/116831072

![dropdown](https://cloud.githubusercontent.com/assets/2703486/5752449/c2c93120-9cb8-11e4-9ba2-f8d1c0119cc5.png)

**Comment by simoncereska** [comment]
Have this issue too.

**Comment by CWSpear** [comment]
I'm confused... it looked like it was working? Where in the 56 second long video is the issue, precisely?

**Comment by simoncereska** [comment]
at 0:11-0:12 you can see, when mouse is on a submenu, it disappears. 

p.s. It looks I solved it by setting bigger z-index, not 100% sure, waiting for feedbacks.

**Comment by CWSpear** [comment]
I guess I see what you're saying... but I can't reproduce this. I tried for 5 minutes on the demo page.

**Comment by CWSpear** [comment]
This is super edgy and hard to reproduce. I'll need a more concrete way to consistently reproduce it to be able to do anything about it.
