### ISSUE TITLE
Usage in the bootstrap navbar, Hover menu shows below the standard dropdown next to it

### ISSUE THREAD

**Issue by warrendodsworth** [CWSpear/bootstrap-hover-dropdown#98]
![hover fix](https://cloud.githubusercontent.com/assets/1066996/5995387/ac7b7c86-aab7-11e4-93e4-345323e83403.jpg)
![hover issue](https://cloud.githubusercontent.com/assets/1066996/5995388/aca61694-aab7-11e4-9289-6d22f0a0fb42.png)

Hello,

When we have the two menu types side by side in the navbar, and the standard one is open, then if we  hover above the hover menu li tag the hover dropdown appears below the standard dropdown menu.

This can be fixed by increasing the z-index of the hover dropdowns parent li element.

<li class="dropdown" style="z-index: 100000000;">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200"><i class="fa fa-fw fa-lg fa-angle-double-down"></i></a>
    <ul class="dropdown-menu">
   </ul>
 </li>

**Comment by CWSpear** [comment]
Ok...? There isn't really an issue here. You can argue the other one should be on the top and thus the "solution" differs case by case, and would be solved in your CSS on a per-project basis.

**Comment by warrendodsworth** [comment]
Not a bug per say, just a thought that it could be optional using a data- attribute 
to either show it on top or below
Or
to disable the hover effect when a standard one is open.

Nice plugin. Quite useful. Thanks.
